Add code in install script to compile lh-path-replace

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,6 +5,43 @@ if [ $# != "1" ]; then
     exit 1
 fi
 
+pushd_quiet () { builtin pushd "$@" > /dev/null; }
+popd_quiet () { builtin popd > /dev/null; }
+
+have_command () {
+    command -v "$1" &> /dev/null
+}
+
+find_compiler () {
+    if [ -z ${CC+x} ]; then
+        if have_command gcc; then
+            echo gcc
+        elif have_command clang; then
+            echo clang
+        else
+            echo "error: cannot find a C compiler."
+            echo "The variable CC is not set and neither gcc or clang are found."
+            exit 1
+        fi
+    else
+        echo "$CC"
+    fi
+}
+
+lhcompile () {
+    local exec_name="$1"
+    if [[ "$OSTYPE" == "msys"* || "$OSTYPE" == "mingw"* ]]; then
+        exec_name="${exec_name}.exe"
+    fi
+    local objs=()
+    for src in "${@:2}"; do
+        obj="${src/%.c/.o}"
+        objs+=("$obj")
+    done
+    $lhcomp -c "$src" -o "$obj"
+    $lhcomp -o $exec_name "${objs[@]}" && rm "${objs[@]}"
+}
+
 PREFIX="$1"
 
 if [ -z "${DESTDIR+x}" ]; then
@@ -14,6 +51,13 @@ fi
 recipes_repo="https://github.com/franko/lhelper-recipes.git"
 recipes_branch=master
 recipes_dir="$DESTDIR/share/lhelper/recipes"
+
+lhcomp="$(find_compiler)"
+
+pushd_quiet src
+echo "compiling lh-path-replace"
+lhcompile lh-path-replace lh-path-replace.c
+popd_quiet
 
 echo "Installing lhelper with prefix $DESTDIR"
 
