Remove remaining references to sed

diff --git a/install-github b/install-github
--- a/install-github
+++ b/install-github
@@ -3,7 +3,41 @@
 version="0.1"
 
 pushd_quiet () { builtin pushd "$@" > /dev/null; }
-popd_quiet () { builtin popd "$@" > /dev/null; }
+popd_quiet () { builtin popd > /dev/null; }
+
+have_command () {
+    command -v "$1" &> /dev/null
+}
+
+find_compiler () {
+    if [ -z ${CC+x} ]; then
+        if have_command gcc; then
+            echo gcc
+        elif have_command clang; then
+            echo clang
+        else
+            echo "error: cannot find a C compiler."
+            echo "The variable CC is not set and neither gcc or clang are found."
+            exit 1
+        fi
+    else
+        echo "$CC"
+    fi
+}
+
+lhcompile () {
+    local exec_name="$1"
+    if [[ "$OSTYPE" == "msys"* || "$OSTYPE" == "mingw"* ]]; then
+        exec_name="${exec_name}.exe"
+    fi
+    local objs=()
+    for src in "${@:2}"; do
+        obj="${src/%.c/.o}"
+        objs+=("$obj")
+    done
+    $lhcomp -c "$src" -o "$obj"
+    $lhcomp -o $exec_name "${objs[@]}" && rm "${objs[@]}"
+}
 
 IFS=':' read -ra path_a <<< "$PATH"
 for name in "${path_a[@]}"; do
@@ -15,6 +49,18 @@ if [ -z ${destdir+set} ]; then
   destdir="$HOME/.local"
   need_path=true
 fi
+
+lhcomp="$(find_compiler)"
+
+pushd_quiet src
+echo "compiling lh-path-replace"
+lhcompile lh-path-replace lh-path-replace.c
+if [ $? -ne 0 ]; then
+    echo "error: cannot compile helper tool lh-path-replace"
+    exit 1
+fi
+cp lh-path-replace "$destdir/bin"
+popd_quiet
 
 echo "Installing using prefix directory $destdir"
 
