fix: check if binary files contains prefix

diff --git a/lhelper b/lhelper
--- a/lhelper
+++ b/lhelper
@@ -161,7 +161,13 @@ library_dir_reloc () {
     local archive_dir="$1"
     local old_prefix="$2"
     local new_prefix="$3"
-    find "$archive_dir" -type f -exec lh-path-replace '{}' "$old_prefix" "$new_prefix" \;
+    find "$archive_dir" -type f -print0 |
+        while IFS= read -r -d '' line; do
+            lh-path-replace "$line" "$old_prefix" "$new_prefix" || {
+                echo "error: prefix directory \"$old_prefix\" found in binary file: \"$line\"" >&2
+                return 1
+            }
+        done
 }
 
 # Extract library archive and relocate prefix path references.
@@ -823,8 +829,9 @@ library_install () {
         fix_pkgconfig_install
         lib_install_msg "done"
 
-        library_dir_reloc "$LHELPER_TEMP_ROOT" "$WIN_INSTALL_PREFIX" "__LHELPER_PREFIX__"
-
+        library_dir_reloc "$LHELPER_TEMP_ROOT" "$WIN_INSTALL_PREFIX" "__LHELPER_PREFIX__" || {
+            exit 1
+        }
         fs_security_delay
         tar -C "$LHELPER_TEMP_ROOT" -czf "${tar_package_filename}" .
         mv "${tar_package_filename}" "$LHELPER_WORKING_DIR/packages"
