Implement version management for packages

diff --git a/lhelper b/lhelper
--- a/lhelper
+++ b/lhelper
@@ -89,14 +89,39 @@ sed_replace_escape () {
     echo "${1//\//\\\/}"
 }
 
+latest_package_version () {
+    local package="$1"
+    cat "$LHELPER_DIR/recipes/index" | while read index_package version
+    do
+        if [[ "$index_package" == "$package" ]]; then
+            echo "$version"
+            return 0
+        fi
+    done
+    return 1
+}
+
 library_install () {
     if [ -z ${LHELPER_ENV_NAME+x} ]; then
         echo "error: no environment defined"
         exit 1
     fi
 
-    if [ ! -f "$LHELPER_DIR/recipes/$1.sh" ]; then
-        echo "error: recipe $1 does not exist."
+    local package="$1"
+    local version
+    if [ -z "$2" ]; then
+        version="$(latest_package_version "$package")"
+        if [ -z "$version" ]; then
+            echo "error: cannot find version number for \"${package}\""
+            exit 1
+        fi
+    else
+        version="$2"
+    fi
+
+    local recipe_filename="${package}_${version}.sh"
+    if [ ! -f "$LHELPER_DIR/recipes/${recipe_filename}" ]; then
+        echo "error: no recipe found for \"${package}\" version ${version}."
         exit 1
     fi
 
@@ -109,7 +134,7 @@ library_install () {
     source "$LHELPER_ENV_PREFIX/bin/lhelper-config"
 
     local digest=$(build_env_digest)
-    local tar_package_filename="$1-${digest}.tar.gz"
+    local tar_package_filename="${package}_${version}_${digest}.tar.gz"
     if [ -f "$LHELPER_WORKING_DIR/packages/${tar_package_filename}" ]; then
         echo "Lhelper: found an existing package"
         echo "Lhelper: extracting package"
@@ -118,7 +143,7 @@ library_install () {
 
         echo "Lhelper: building library..."
         # Execute the recipe
-        bash -e "$LHELPER_DIR/recipes/$1.sh"
+        bash -e "$LHELPER_DIR/recipes/${recipe_filename}" "${package}" "${version}"
         if [ $? -ne 0 ]; then
             echo "Lhelper: error building library \"$1\""
             exit 1
@@ -147,14 +172,14 @@ create_env () {
 case $1 in
 install)
     if [ $# -lt 2 ]; then
-        echo "Usage: $LHELPER_COMMAND_NAME install <library-name>"
+        echo "Usage: $LHELPER_COMMAND_NAME install <library-name> [version]"
         exit 1
     fi
     if [ -z ${LHELPER_ENV_NAME+x} ]; then
         echo "Please activate an environment before."
         exit 1
     fi
-    library_install "$2"
+    library_install "${@:2}"
     ;;
 activate)
     if [ $# -lt 2 ]; then
