feat: add specific code for config errors
Implemented in SDL2 recipe to report an error about the configuration
which is not acceptable because on linux we need at least one between
x11 or wayland video support.

diff --git a/lhelper b/lhelper
--- a/lhelper
+++ b/lhelper
@@ -921,6 +921,11 @@ library_install () {
             cat "$log_dirname/$package-stderr.log"
             exit 1
             ;;
+        7)
+            echo "Error in the configuration for $package:"; echo
+            cat "$log_dirname/$package-stderr.log"
+            exit 1
+            ;;
         *)
             echo "error: building library \"$package\""
             echo "    You may inspect the log files:"
