Error out if there are unmet dependencies
By installing unmet dependencies automatically we lose some control.

If a dependency is provided by the system we may still want to
install the corresponding lhelper package to avoid using the system library.

We may add into the future an option to automatically fetch dependencies.

diff --git a/lhelper b/lhelper
--- a/lhelper
+++ b/lhelper
@@ -672,14 +672,14 @@ install)
     # get dependencies
     library_install dependencies "${@:2}"
     if [[ ${#_missing[@]} -ne 0 ]]; then
-        echo "Found missing packages"
+        echo "Found missing packages:"; echo
         for line in "${_missing[@]}"; do
-            echo "Installing missing package: $line"
-            # no quoting below for $line, we need to break on spaces
-            library_install run $line || exit 1
+            echo "- $line"
         done
+        echo; echo "The package $2 cannot be installed due to missing dependencies."
+        exit 1
     fi
-    echo "Install the requested package: ${@:2}"
+    echo "Installing the requested package: ${@:2}"
     library_install run "${@:2}"
     unset _missing
     ;;
